<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PriceCompare.Core\PriceCompare.Core.csproj" />
    <ProjectReference Include="..\PriceCompare.Application\PriceCompare.Application.csproj" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>
</Project>
